
import { Perfume } from './types';

export const INITIAL_PERFUMES: Perfume[] = [
  // --- FLORAL (13 total) ---
  { id: 'fl-1', name: 'Miss Dior', brand: 'Dior', gender: 'Female', concentration: 'EDP', scentFamily: 'Floral', topNotes: ['Iris', 'Peony', 'Lily-of-the-Valley'], middleNotes: ['Apricot', 'Rose', 'Peach'], baseNotes: ['Vanilla', 'Musk', 'Tonka Bean', 'Benzoin', 'Sandalwood'], longevity: 4, sillage: 3, intensity: 3, price: 3500, season: ['Spring', 'Summer'], occasion: 'Day' },
  { id: 'fl-2', name: 'J adore', brand: 'Dior', gender: 'Female', concentration: 'EDP', scentFamily: 'Floral', topNotes: ['Pear', 'Melon', 'Magnolia', 'Peach', 'Mandarin Orange', 'Bergamot'], middleNotes: ['Jasmine', 'Lily-of-the-Valley', 'Tuberose', 'Freesia', 'Rose', 'Orchid', 'Plum', 'Violet'], baseNotes: ['Musk', 'Vanilla', 'Blackberry', 'Cedar'], longevity: 4, sillage: 4, intensity: 4, price: 4200, season: ['Spring', 'Autumn'], occasion: 'Special' },
  { id: 'fl-3', name: 'Flowerbomb', brand: 'Viktor&Rolf', gender: 'Female', concentration: 'EDP', scentFamily: 'Floral', topNotes: ['Tea', 'Bergamot', 'Osmanthus'], middleNotes: ['Orchid', 'Jasmine', 'Rose', 'Freesia', 'African Orange Flower'], baseNotes: ['Patchouli', 'Musk', 'Vanilla'], longevity: 5, sillage: 5, intensity: 5, price: 4800, season: ['Autumn', 'Winter'], occasion: 'Night' },
  { id: 'fl-4', name: 'Gucci Bloom', brand: 'Gucci', gender: 'Female', concentration: 'EDP', scentFamily: 'Floral', topNotes: ['Jasmine'], middleNotes: ['Tuberose'], baseNotes: ['Rangoon creeper'], longevity: 4, sillage: 4, intensity: 3, price: 3800, season: ['Spring', 'Summer'], occasion: 'Day' },
  { id: 'fl-5', name: 'Chloé Eau de Parfum', brand: 'Chloé', gender: 'Female', concentration: 'EDP', scentFamily: 'Floral', topNotes: ['Peony', 'Lychee', 'Freesia'], middleNotes: ['Rose', 'Lily-of-the-Valley', 'Magnolia'], baseNotes: ['Virginia Cedar', 'Amber'], longevity: 4, sillage: 3, intensity: 3, price: 3200, season: ['Spring'], occasion: 'Office' },
  { id: 'fl-6', name: 'Carnal Flower', brand: 'Frederic Malle', gender: 'Unisex', concentration: 'EDP', scentFamily: 'Floral', topNotes: ['Bergamot', 'Melon', 'Eucalyptus'], middleNotes: ['Tuberose', 'Ylang-Ylang', 'Jasmine'], baseNotes: ['White Musk', 'Coconut'], longevity: 5, sillage: 5, intensity: 5, price: 12000, season: ['Summer', 'Autumn'], occasion: 'Special' },
  { id: 'fl-7', name: 'Black Opium', brand: 'YSL', gender: 'Female', concentration: 'EDP', scentFamily: 'Floral', topNotes: ['Pear', 'Pink Pepper', 'Orange Blossom'], middleNotes: ['Coffee', 'Jasmine', 'Bitter Almond', 'Licorice'], baseNotes: ['Vanilla', 'Patchouli', 'Cedar', 'Cashmere Wood'], longevity: 4, sillage: 4, intensity: 4, price: 4100, season: ['Winter', 'Autumn'], occasion: 'Night' },
  { id: 'fl-8', name: 'La Vie Est Belle', brand: 'Lancôme', gender: 'Female', concentration: 'EDP', scentFamily: 'Floral', topNotes: ['Blackcurrant', 'Pear'], middleNotes: ['Iris', 'Jasmine', 'Orange Blossom'], baseNotes: ['Praline', 'Vanilla', 'Patchouli', 'Tonka Bean'], longevity: 5, sillage: 5, intensity: 4, price: 3900, season: ['Winter', 'Autumn'], occasion: 'Special' },
  { id: 'fl-9', name: 'Good Girl', brand: 'Carolina Herrera', gender: 'Female', concentration: 'EDP', scentFamily: 'Floral', topNotes: ['Almond', 'Coffee', 'Bergamot', 'Lemon'], middleNotes: ['Jasmine Sambac', 'Tuberose', 'Orris', 'Bulgarian Rose', 'Orange Blossom'], baseNotes: ['Tonka Bean', 'Cacao', 'Sandalwood', 'Vanilla', 'Praline', 'Cinnamon', 'Cedar', 'Cashmere Wood', 'Patchouli', 'Amber', 'Musk'], longevity: 4, sillage: 4, intensity: 4, price: 4500, season: ['Autumn', 'Winter'], occasion: 'Date' },
  { id: 'fl-10', name: 'Daisy', brand: 'Marc Jacobs', gender: 'Female', concentration: 'EDT', scentFamily: 'Floral', topNotes: ['Violet Leaf', 'Blood Grapefruit', 'Strawberry'], middleNotes: ['Gardenia', 'Violet', 'Jasmine'], baseNotes: ['Musk', 'White Woods', 'Vanilla'], longevity: 3, sillage: 2, intensity: 2, price: 2800, season: ['Spring', 'Summer'], occasion: 'Day' },
  { id: 'fl-11', name: 'Pure Poison', brand: 'Dior', gender: 'Female', concentration: 'EDP', scentFamily: 'Floral', topNotes: ['Jasmine', 'Orange', 'Bergamot', 'Sicilian Mandarin'], middleNotes: ['Gardenia', 'Orange Blossom'], baseNotes: ['Sandalwood', 'White Amber', 'Cedar', 'White Musk'], longevity: 5, sillage: 4, intensity: 4, price: 4600, season: ['Winter', 'Spring'], occasion: 'Night' },
  { id: 'fl-12', name: 'Flora Gorgeous Gardenia', brand: 'Gucci', gender: 'Female', concentration: 'EDP', scentFamily: 'Floral', topNotes: ['Pear Blossom', 'Red Berries', 'Italian Mandarin'], middleNotes: ['Gardenia', 'Jasmine', 'Frangipani'], baseNotes: ['Brown Sugar', 'Patchouli'], longevity: 3, sillage: 3, intensity: 3, price: 3700, season: ['Spring', 'Summer'], occasion: 'Day' },
  { id: 'fl-13', name: 'Idôle', brand: 'Lancôme', gender: 'Female', concentration: 'EDP', scentFamily: 'Floral', topNotes: ['Pear', 'Bergamot', 'Pink Pepper'], middleNotes: ['Rose', 'Jasmine'], baseNotes: ['White Musk', 'Vanilla', 'Patchouli', 'Cedar'], longevity: 4, sillage: 3, intensity: 3, price: 3400, season: ['Spring', 'Summer'], occasion: 'Office' },

  // --- WOODY (13 total) ---
  { id: 'wd-1', name: 'Bleu de Chanel', brand: 'Chanel', gender: 'Male', concentration: 'Parfum', scentFamily: 'Woody', topNotes: ['Lemon Zest', 'Bergamot', 'Mint', 'Artemisia'], middleNotes: ['Lavender', 'Pineapple', 'Geranium', 'Green Notes'], baseNotes: ['Sandalwood', 'Cedar', 'Amberwood', 'Iso E Super', 'Tonka Bean'], longevity: 5, sillage: 3, intensity: 4, price: 5500, season: ['Autumn', 'Winter', 'Spring'], occasion: 'Office' },
  { id: 'wd-2', name: 'Terre d Hermes', brand: 'Hermès', gender: 'Male', concentration: 'EDT', scentFamily: 'Woody', topNotes: ['Orange', 'Grapefruit'], middleNotes: ['Pepper', 'Pelargonium'], baseNotes: ['Vetiver', 'Cedar', 'Patchouli', 'Benzoin'], longevity: 4, sillage: 3, intensity: 4, price: 3200, season: ['Spring', 'Autumn'], occasion: 'Office' },
  { id: 'wd-3', name: 'Santal 33', brand: 'Le Labo', gender: 'Unisex', concentration: 'EDP', scentFamily: 'Woody', topNotes: ['Cardamom', 'Iris', 'Violet'], middleNotes: ['Australian Sandalwood', 'Papyrus', 'Cedarwood'], baseNotes: ['Leather', 'Ambrosia', 'Musk'], longevity: 5, sillage: 4, intensity: 4, price: 9800, season: ['Autumn', 'Winter', 'Spring'], occasion: 'Special' },
  { id: 'wd-4', name: 'Oud Wood', brand: 'Tom Ford', gender: 'Unisex', concentration: 'EDP', scentFamily: 'Woody', topNotes: ['Rosewood', 'Cardamom', 'Chinese Pepper'], middleNotes: ['Oud', 'Sandalwood', 'Vetiver'], baseNotes: ['Tonka Bean', 'Vanilla', 'Amber'], longevity: 4, sillage: 3, intensity: 4, price: 8500, season: ['Winter', 'Autumn'], occasion: 'Night' },
  { id: 'wd-5', name: 'Encre Noire', brand: 'Lalique', gender: 'Male', concentration: 'EDT', scentFamily: 'Woody', topNotes: ['Cypress'], middleNotes: ['Vetiver'], baseNotes: ['Cashmere Wood', 'Musk'], longevity: 4, sillage: 3, intensity: 4, price: 1800, season: ['Autumn', 'Winter'], occasion: 'Special' },
  { id: 'wd-6', name: 'Wonderwood', brand: 'Comme des Garcons', gender: 'Unisex', concentration: 'EDP', scentFamily: 'Woody', topNotes: ['Bergamot', 'Madagascar Pepper', 'Nutmeg'], middleNotes: ['Cristalon', 'Cashmeran', 'Guaiac Wood', 'Cedar'], baseNotes: ['Javanol', 'Sandalwood', 'Vetiver', 'Oud'], longevity: 4, sillage: 3, intensity: 4, price: 4200, season: ['Autumn', 'Winter'], occasion: 'Office' },
  { id: 'wd-7', name: 'Tam Dao', brand: 'Diptyque', gender: 'Unisex', concentration: 'EDP', scentFamily: 'Woody', topNotes: ['Rose', 'Myrtle', 'Italian Cypress'], middleNotes: ['Sandalwood', 'Cedar'], baseNotes: ['Spices', 'Amber', 'White Musk', 'Brazilian Rosewood'], longevity: 4, sillage: 3, intensity: 3, price: 5800, season: ['Autumn', 'Winter', 'Spring'], occasion: 'Day' },
  { id: 'wd-8', name: 'Molecule 01', brand: 'Escentric Molecules', gender: 'Unisex', concentration: 'EDT', scentFamily: 'Woody', topNotes: ['Iso E Super'], middleNotes: ['Iso E Super'], baseNotes: ['Iso E Super'], longevity: 5, sillage: 2, intensity: 1, price: 4500, season: ['Spring', 'Summer', 'Autumn', 'Winter'], occasion: 'Office' },
  { id: 'wd-9', name: 'Sycomore', brand: 'Chanel', gender: 'Unisex', concentration: 'EDP', scentFamily: 'Woody', topNotes: ['Aldehydes'], middleNotes: ['Vetiver', 'Tobacco', 'Juniper'], baseNotes: ['Sandalwood', 'Pink Pepper', 'Spices'], longevity: 5, sillage: 4, intensity: 4, price: 11000, season: ['Autumn', 'Winter'], occasion: 'Special' },
  { id: 'wd-10', name: 'Gipsy Water', brand: 'Byredo', gender: 'Unisex', concentration: 'EDP', scentFamily: 'Woody', topNotes: ['Bergamot', 'Lemon', 'Pepper', 'Juniper Berries'], middleNotes: ['Incense', 'Pine Needles', 'Orris Root'], baseNotes: ['Amber', 'Vanilla', 'Sandalwood'], longevity: 3, sillage: 2, intensity: 2, price: 7200, season: ['Spring', 'Summer'], occasion: 'Day' },
  { id: 'wd-11', name: 'Wood Sage & Sea Salt', brand: 'Jo Malone', gender: 'Unisex', concentration: 'Cologne', scentFamily: 'Woody', topNotes: ['Ambrette Seeds'], middleNotes: ['Sea Salt'], baseNotes: ['Sage'], longevity: 2, sillage: 2, intensity: 2, price: 5400, season: ['Summer', 'Spring'], occasion: 'Day' },
  { id: 'wd-12', name: 'Gentleman Reserve Privée', brand: 'Givenchy', gender: 'Male', concentration: 'EDP', scentFamily: 'Woody', topNotes: ['Bergamot'], middleNotes: ['Iris', 'Chestnut'], baseNotes: ['Whiskey', 'Woody Notes', 'Amber'], longevity: 4, sillage: 4, intensity: 4, price: 4300, season: ['Winter', 'Autumn'], occasion: 'Night' },
  { id: 'wd-13', name: 'Explorer', brand: 'Montblanc', gender: 'Male', concentration: 'EDP', scentFamily: 'Woody', topNotes: ['Bergamot', 'Pink Pepper', 'Clary Sage'], middleNotes: ['Haitian Vetiver', 'Leather'], baseNotes: ['Ambroxan', 'Akigalawood', 'Indonesian Patchouli Leaf', 'Cacao Pod'], longevity: 4, sillage: 3, intensity: 3, price: 2900, season: ['Spring', 'Autumn', 'Summer'], occasion: 'Office' },

  // --- ORIENTAL (12 total) ---
  { id: 'or-1', name: 'Black Orchid', brand: 'Tom Ford', gender: 'Unisex', concentration: 'EDP', scentFamily: 'Oriental', topNotes: ['Truffle', 'Gardenia', 'Blackcurrant', 'Ylang-Ylang', 'Jasmine', 'Bergamot', 'Mandarin Orange', 'Amalfi Lemon'], middleNotes: ['Orchid', 'Spices', 'Gardenia', 'Fruity Notes', 'Ylang-Ylang', 'Jasmine', 'Lotus'], baseNotes: ['Mexican Chocolate', 'Patchouli', 'Vanille', 'Incense', 'Amber', 'Sandalwood', 'Vetiver', 'White Musk'], longevity: 5, sillage: 5, intensity: 5, price: 6200, season: ['Winter', 'Autumn'], occasion: 'Night' },
  { id: 'or-2', name: 'Tobacco Vanille', brand: 'Tom Ford', gender: 'Unisex', concentration: 'EDP', scentFamily: 'Oriental', topNotes: ['Tobacco Leaf', 'Spicy Notes'], middleNotes: ['Vanilla', 'Cacao', 'Tonka Bean', 'Tobacco Blossom'], baseNotes: ['Dried Fruits', 'Woody Notes'], longevity: 5, sillage: 5, intensity: 5, price: 11500, season: ['Winter'], occasion: 'Date' },
  { id: 'or-3', name: 'Shalimar', brand: 'Guerlain', gender: 'Female', concentration: 'EDP', scentFamily: 'Oriental', topNotes: ['Citrus', 'Bergamot', 'Lemon', 'Cedar', 'Mandarin Orange'], middleNotes: ['Iris', 'Patchouli', 'Jasmine', 'Rose'], baseNotes: ['Vanilla', 'Incense', 'Leather', 'Opoponax', 'Sandalwood', 'Civet', 'Musk', 'Tonka Bean'], longevity: 5, sillage: 5, intensity: 5, price: 4200, season: ['Winter'], occasion: 'Special' },
  { id: 'or-4', name: 'Opium', brand: 'YSL', gender: 'Female', concentration: 'EDP', scentFamily: 'Oriental', topNotes: ['Cloves', 'Pepper', 'Coriander', 'Indonesian West Bay Leaf', 'Plum', 'Jasmine', 'Mandarin Orange', 'Citrues', 'Bergamot'], middleNotes: ['Carnation', 'Cinnamon', 'Sandalwood', 'Patchouli', 'Orris Root', 'Rose', 'Peach', 'Lily-of-the-Valley'], baseNotes: ['Incense', 'Myrrh', 'Sandalwood', 'Tolu Balsam', 'Amber', 'Benzoin', 'Opoponax', 'Vanilla', 'Castoreum', 'Cedar', 'Vetiver', 'Coconut', 'Musk'], longevity: 5, sillage: 5, intensity: 5, price: 4800, season: ['Winter', 'Autumn'], occasion: 'Night' },
  { id: 'or-5', name: 'Ambre Nuit', brand: 'Dior', gender: 'Unisex', concentration: 'EDP', scentFamily: 'Oriental', topNotes: ['Bergamot', 'Grapefruit'], middleNotes: ['Damask Rose', 'Pink Pepper'], baseNotes: ['Ambergris', 'Guaiac Wood', 'Cedar', 'Patchouli'], longevity: 4, sillage: 3, intensity: 3, price: 11000, season: ['Autumn', 'Winter'], occasion: 'Date' },
  { id: 'or-6', name: 'Grand Soir', brand: 'Maison Francis Kurkdjian', gender: 'Unisex', concentration: 'EDP', scentFamily: 'Oriental', topNotes: ['Spanish Labdanum'], middleNotes: ['Siam Benzoin', 'Tonka Bean'], baseNotes: ['Amber', 'Vanilla'], longevity: 5, sillage: 5, intensity: 5, price: 8200, season: ['Winter', 'Autumn'], occasion: 'Night' },
  { id: 'or-7', name: 'L air du Desert Marocain', brand: 'Tauer Perfumes', gender: 'Unisex', concentration: 'EDP', scentFamily: 'Oriental', topNotes: ['Coriander', 'Cumin', 'Petitgrain', 'Lavender'], middleNotes: ['Jasmine', 'Birch', 'Rock Rose', 'Geranium'], baseNotes: ['Amber', 'Cedar', 'Vetiver', 'Patchouli', 'Oakmoss'], longevity: 5, sillage: 5, intensity: 5, price: 6500, season: ['Autumn', 'Winter'], occasion: 'Special' },
  { id: 'or-8', name: 'Portrait of a Lady', brand: 'Frederic Malle', gender: 'Female', concentration: 'EDP', scentFamily: 'Oriental', topNotes: ['Rose', 'Clove', 'Raspberry', 'Blackcurrant', 'Cinnamon'], middleNotes: ['Patchouli', 'Incense', 'Sandalwood'], baseNotes: ['Musk', 'Benzoin', 'Amber'], longevity: 5, sillage: 5, intensity: 5, price: 13500, season: ['Winter', 'Autumn'], occasion: 'Special' },
  { id: 'or-9', name: 'Spicebomb Extreme', brand: 'Viktor&Rolf', gender: 'Male', concentration: 'EDP', scentFamily: 'Oriental', topNotes: ['Black Pepper', 'Caraway'], middleNotes: ['Grapefruit'], baseNotes: ['Tobacco', 'Vanilla'], longevity: 5, sillage: 5, intensity: 5, price: 4200, season: ['Winter', 'Autumn'], occasion: 'Night' },
  { id: 'or-10', name: 'Layton', brand: 'Parfums de Marly', gender: 'Unisex', concentration: 'EDP', scentFamily: 'Oriental', topNotes: ['Apple', 'Lavender', 'Bergamot', 'Mandarin Orange'], middleNotes: ['Geranium', 'Violet', 'Jasmine'], baseNotes: ['Vanilla', 'Cardamom', 'Sandalwood', 'Pepper', 'Patchouli', 'Guaiac Wood'], longevity: 5, sillage: 4, intensity: 4, price: 9200, season: ['Winter', 'Autumn', 'Spring'], occasion: 'Special' },
  { id: 'or-11', name: 'Side Effect', brand: 'Initio Parfums Prives', gender: 'Unisex', concentration: 'EDP', scentFamily: 'Oriental', topNotes: ['Rum'], middleNotes: ['Tobacco', 'Vanilla'], baseNotes: ['Cinnamon'], longevity: 5, sillage: 5, intensity: 5, price: 10500, season: ['Winter', 'Autumn'], occasion: 'Night' },
  { id: 'or-12', name: 'Angels Share', brand: 'By Kilian', gender: 'Unisex', concentration: 'EDP', scentFamily: 'Oriental', topNotes: ['Cognac'], middleNotes: ['Cinnamon', 'Tonka Bean', 'Oak'], baseNotes: ['Praline', 'Vanilla', 'Sandalwood'], longevity: 5, sillage: 4, intensity: 4, price: 8800, season: ['Winter', 'Autumn'], occasion: 'Date' },

  // --- FRESH (12 total) ---
  { id: 'fr-1', name: 'Acqua di Gio', brand: 'Giorgio Armani', gender: 'Male', concentration: 'EDT', scentFamily: 'Fresh', topNotes: ['Lime', 'Lemon', 'Bergamot', 'Jasmine', 'Orange', 'Mandarin Orange', 'Neroli'], middleNotes: ['Sea Notes', 'Jasmine', 'Calone', 'Peach', 'Freesia', 'Cyclamen', 'Hyacinth', 'Violet', 'Rose', 'Coriander', 'Rosemary'], baseNotes: ['White Musk', 'Cedar', 'Oakmoss', 'Patchouli', 'Amber'], longevity: 3, sillage: 3, intensity: 2, price: 2800, season: ['Summer'], occasion: 'Day' },
  { id: 'fr-2', name: 'Bright Crystal', brand: 'Versace', gender: 'Female', concentration: 'EDT', scentFamily: 'Fresh', topNotes: ['Yuzu', 'Pomegranate', 'Ice'], middleNotes: ['Peony', 'Lotus', 'Magnolia'], baseNotes: ['Musk', 'Mahogany', 'Amber'], longevity: 3, sillage: 3, intensity: 2, price: 2200, season: ['Summer', 'Spring'], occasion: 'Office' },
  { id: 'fr-3', name: 'Cool Water', brand: 'Davidoff', gender: 'Male', concentration: 'EDT', scentFamily: 'Fresh', topNotes: ['Sea water', 'Mint', 'Green Notes', 'Lavender', 'Coriander', 'Rosemary', 'Calone'], middleNotes: ['Sandalwood', 'Jasmine', 'Neroli', 'Geranium'], baseNotes: ['Musk', 'Oakmoss', 'Cedar', 'Tobacco', 'Amber'], longevity: 3, sillage: 3, intensity: 3, price: 1200, season: ['Summer'], occasion: 'Day' },
  { id: 'fr-4', name: 'Silver Mountain Water', brand: 'Creed', gender: 'Unisex', concentration: 'EDP', scentFamily: 'Fresh', topNotes: ['Bergamot', 'Mandarin Orange'], middleNotes: ['Green Tea', 'Blackcurrant'], baseNotes: ['Musk', 'Petitgrain', 'Sandalwood', 'Galbanum'], longevity: 4, sillage: 3, intensity: 3, price: 11500, season: ['Spring', 'Summer'], occasion: 'Day' },
  { id: 'fr-5', name: 'L Eau d Issey', brand: 'Issey Miyake', gender: 'Female', concentration: 'EDT', scentFamily: 'Fresh', topNotes: ['Lotus', 'Melon', 'Freesia', 'Rose Water', 'Rose', 'Calone', 'Cyclamen'], middleNotes: ['Lily', 'Lily-of-the-Valley', 'Water Peony', 'Carnation'], baseNotes: ['Musk', 'Tuberose', 'Exotic Woods', 'Osmanthus', 'Cedar', 'Amber', 'Sandalwood'], longevity: 4, sillage: 4, intensity: 3, price: 2400, season: ['Summer', 'Spring'], occasion: 'Day' },
  { id: 'fr-6', name: 'Allure Homme Sport', brand: 'Chanel', gender: 'Male', concentration: 'EDT', scentFamily: 'Fresh', topNotes: ['Orange', 'Sea Notes', 'Aldehydes', 'Blood Mandarin'], middleNotes: ['Pepper', 'Neroli', 'Cedar'], baseNotes: ['Tonka Bean', 'Vanilla', 'White Musk', 'Amber', 'Vetiver', 'Elemi resin'], longevity: 4, sillage: 4, intensity: 3, price: 4600, season: ['Summer', 'Spring'], occasion: 'Day' },
  { id: 'fr-7', name: 'Eau Sauvage', brand: 'Dior', gender: 'Male', concentration: 'EDT', scentFamily: 'Fresh', topNotes: ['Lemon', 'Bergamot', 'Basil', 'Rosemary', 'Caraway', 'Fruity Notes'], middleNotes: ['Jasmine', 'Coriander', 'Patchouli', 'Orris Root', 'Carnation', 'Sandalwood', 'Rose'], baseNotes: ['Oakmoss', 'Vetiver', 'Musk', 'Amber'], longevity: 3, sillage: 3, intensity: 3, price: 3800, season: ['Summer', 'Spring'], occasion: 'Office' },
  { id: 'fr-8', name: 'Bleu de Chanel EDT', brand: 'Chanel', gender: 'Male', concentration: 'EDT', scentFamily: 'Fresh', topNotes: ['Lemon', 'Mint', 'Pink Pepper', 'Grapefruit'], middleNotes: ['Ginger', 'Iso E Super', 'Jasmine', 'Nutmeg'], baseNotes: ['Labdanum', 'Sandalwood', 'Patchouli', 'Vetiver', 'Incense', 'Cedar', 'White Musk'], longevity: 4, sillage: 3, intensity: 3, price: 4100, season: ['Spring', 'Summer'], occasion: 'Office' },
  { id: 'fr-9', name: 'Hacivat', brand: 'Nishane', gender: 'Unisex', concentration: 'Extrait', scentFamily: 'Fresh', topNotes: ['Pineapple', 'Grapefruit', 'Bergamot'], middleNotes: ['Cedar', 'Patchouli', 'Jasmine'], baseNotes: ['Oakmoss', 'Woody Notes'], longevity: 5, sillage: 5, intensity: 5, price: 7500, season: ['Summer', 'Spring', 'Autumn'], occasion: 'Special' },
  { id: 'fr-10', name: 'Aventus', brand: 'Creed', gender: 'Male', concentration: 'EDP', scentFamily: 'Fresh', topNotes: ['Pineapple', 'Bergamot', 'Blackcurrant', 'Apple'], middleNotes: ['Birch', 'Patchouli', 'Moroccan Jasmine', 'Rose'], baseNotes: ['Musk', 'Oakmoss', 'Ambergris', 'Vanille'], longevity: 5, sillage: 4, intensity: 4, price: 14500, season: ['Spring', 'Summer', 'Autumn'], occasion: 'Special' },
  { id: 'fr-11', name: 'Aqua Allegoria Herba Fresca', brand: 'Guerlain', gender: 'Unisex', concentration: 'EDT', scentFamily: 'Fresh', topNotes: ['Lemon', 'Clover'], middleNotes: ['Mint', 'Green Tea'], baseNotes: ['Lily of the Valley', 'Cyclamen'], longevity: 2, sillage: 2, intensity: 2, price: 3200, season: ['Summer'], occasion: 'Day' },
  { id: 'fr-12', name: 'Ocean Leather', brand: 'Memo Paris', gender: 'Unisex', concentration: 'EDP', scentFamily: 'Fresh', topNotes: ['Mandarin Orange', 'Basil', 'Violet'], middleNotes: ['Sage', 'Elemi', 'Cedar'], baseNotes: ['Leather', 'Vetiver', 'Nutmeg'], longevity: 4, sillage: 3, intensity: 4, price: 9500, season: ['Spring', 'Autumn'], occasion: 'Special' },

  // --- CITRUS (11 total) ---
  { id: 'ct-1', name: 'Light Blue', brand: 'Dolce&Gabbana', gender: 'Female', concentration: 'EDT', scentFamily: 'Citrus', topNotes: ['Sicilian Lemon', 'Apple', 'Cedar', 'Bellflower'], middleNotes: ['Bamboo', 'Jasmine', 'White Rose'], baseNotes: ['Cedar', 'Musk', 'Amber'], longevity: 3, sillage: 2, intensity: 2, price: 2500, season: ['Summer'], occasion: 'Day' },
  { id: 'ct-2', name: 'Bergamote 22', brand: 'Le Labo', gender: 'Unisex', concentration: 'EDP', scentFamily: 'Citrus', topNotes: ['Bergamot', 'Grapefruit'], middleNotes: ['Petitgrain', 'Orange Blossom'], baseNotes: ['Vetiver', 'Cedar', 'Musk', 'Amber'], longevity: 3, sillage: 3, intensity: 3, price: 8800, season: ['Summer'], occasion: 'Day' },
  { id: 'ct-3', name: 'Orange Sanguine', brand: 'Atelier Cologne', gender: 'Unisex', concentration: 'Cologne', scentFamily: 'Citrus', topNotes: ['Blood Orange', 'Bitter Orange'], middleNotes: ['Jasmine', 'Geranium'], baseNotes: ['Sandalwood', 'Amber', 'Tonka Bean'], longevity: 3, sillage: 3, intensity: 3, price: 4200, season: ['Summer'], occasion: 'Day' },
  { id: 'ct-4', name: 'Neroli Portofino', brand: 'Tom Ford', gender: 'Unisex', concentration: 'EDP', scentFamily: 'Citrus', topNotes: ['Bergamot', 'Mandarin Orange', 'Lemon', 'Bitter Orange', 'Lavender', 'Rosemary', 'Myrtle'], middleNotes: ['African Orange Flower', 'Neroli', 'Jasmine', 'Pittosporum'], baseNotes: ['Amber', 'Angelica', 'Ambrette'], longevity: 3, sillage: 3, intensity: 3, price: 7200, season: ['Summer'], occasion: 'Day' },
  { id: 'ct-5', name: 'Lemon Line', brand: 'Mancera', gender: 'Unisex', concentration: 'EDP', scentFamily: 'Citrus', topNotes: ['Lemon', 'Orange', 'Lavender'], middleNotes: ['White Flowers', 'Geranium', 'Amber'], baseNotes: ['Oakmoss', 'White Musk'], longevity: 4, sillage: 4, intensity: 4, price: 3400, season: ['Summer'], occasion: 'Day' },
  { id: 'ct-6', name: 'Renaissance', brand: 'Xerjoff', gender: 'Unisex', concentration: 'EDP', scentFamily: 'Citrus', topNotes: ['Amalfi Lemon', 'Tangerine', 'Bergamot', 'Petitgrain'], middleNotes: ['Mint', 'Lily-of-the-Valley', 'Rose'], baseNotes: ['Musk', 'Cedar', 'Amber', 'Patchouli'], longevity: 4, sillage: 4, intensity: 4, price: 6800, season: ['Summer', 'Spring'], occasion: 'Day' },
  { id: 'ct-7', name: 'Cedrat Boise', brand: 'Mancera', gender: 'Unisex', concentration: 'EDP', scentFamily: 'Citrus', topNotes: ['Sicilian Lemon', 'Blackcurrant', 'Bergamot', 'Spices'], middleNotes: ['Fruity Notes', 'Patchouli Leaf', 'Water Jasmine'], baseNotes: ['Cedar', 'Leather', 'Sandalwood', 'Vanilla', 'Moss', 'White Musk'], longevity: 5, sillage: 4, intensity: 4, price: 3600, season: ['Spring', 'Summer', 'Autumn'], occasion: 'Office' },
  { id: 'ct-8', name: 'Acqua Viva', brand: 'Profumum Roma', gender: 'Unisex', concentration: 'Parfum', scentFamily: 'Citrus', topNotes: ['Amalfi Lemon'], middleNotes: ['Cypress', 'Labdanum'], baseNotes: ['Cedar'], longevity: 5, sillage: 4, intensity: 5, price: 7800, season: ['Summer'], occasion: 'Day' },
  { id: 'ct-9', name: 'Arancia di Capri', brand: 'Acqua di Parma', gender: 'Unisex', concentration: 'EDT', scentFamily: 'Citrus', topNotes: ['Orange', 'Sicilian Mandarin', 'Lemon', 'Bergamot'], middleNotes: ['Petitgrain', 'Cardamom'], baseNotes: ['Caramel', 'Musk'], longevity: 2, sillage: 2, intensity: 2, price: 3100, season: ['Summer'], occasion: 'Day' },
  { id: 'ct-10', name: 'Yuzu Man', brand: 'Caron', gender: 'Male', concentration: 'EDT', scentFamily: 'Citrus', topNotes: ['Yuzu', 'Verbena', 'Basil'], middleNotes: ['Fig', 'Pistachio', 'Lentisque'], baseNotes: ['Sandalwood', 'Cedar', 'Guaiac Wood'], longevity: 3, sillage: 3, intensity: 3, price: 2200, season: ['Summer'], occasion: 'Day' },
  { id: 'ct-11', name: 'Eau d Orange Verte', brand: 'Hermès', gender: 'Unisex', concentration: 'EDC', scentFamily: 'Citrus', topNotes: ['Orange', 'Lemon', 'Mandarin'], middleNotes: ['Mint', 'Blackcurrant bud'], baseNotes: ['Oakmoss', 'Patchouli'], longevity: 2, sillage: 2, intensity: 2, price: 2900, season: ['Summer'], occasion: 'Day' },

  // --- SPICY (10 total) ---
  { id: 'sp-1', name: 'Spicebomb', brand: 'Viktor&Rolf', gender: 'Male', concentration: 'EDT', scentFamily: 'Spicy', topNotes: ['Pink Pepper', 'Elemi', 'Bergamot', 'Grapefruit'], middleNotes: ['Cinnamon', 'Saffron', 'Paprika'], baseNotes: ['Tobacco', 'Leather', 'Vetiver'], longevity: 4, sillage: 4, intensity: 4, price: 3200, season: ['Winter', 'Autumn'], occasion: 'Night' },
  { id: 'sp-2', name: 'Sauvage Elixir', brand: 'Dior', gender: 'Male', concentration: 'Parfum', scentFamily: 'Spicy', topNotes: ['Cinnamon', 'Nutmeg', 'Cardamom', 'Grapefruit'], middleNotes: ['Lavender'], baseNotes: ['Licorice', 'Sandalwood', 'Amber', 'Patchouli', 'Haitian Vetiver'], longevity: 5, sillage: 5, intensity: 5, price: 5800, season: ['Winter', 'Autumn'], occasion: 'Special' },
  { id: 'sp-3', name: 'Musc Ravageur', brand: 'Frederic Malle', gender: 'Unisex', concentration: 'EDP', scentFamily: 'Spicy', topNotes: ['Lavender', 'Tangerine', 'Bergamot'], middleNotes: ['Cinnamon', 'Cloves'], baseNotes: ['Vanilla', 'Musk', 'Tonka Bean', 'Amber', 'Sandalwood', 'Guaiac Wood', 'Cedar'], longevity: 5, sillage: 4, intensity: 4, price: 11000, season: ['Winter', 'Autumn'], occasion: 'Date' },
  { id: 'sp-4', name: 'Poivre Samarcande', brand: 'Hermès', gender: 'Unisex', concentration: 'EDT', scentFamily: 'Spicy', topNotes: ['Black Pepper', 'Chili Pepper'], middleNotes: ['Oak', 'Caraway'], baseNotes: ['Cedar', 'Patchouli', 'Moss'], longevity: 4, sillage: 3, intensity: 3, price: 9500, season: ['Autumn', 'Winter'], occasion: 'Office' },
  { id: 'sp-5', name: 'Fate Man', brand: 'Amouage', gender: 'Male', concentration: 'EDP', scentFamily: 'Spicy', topNotes: ['Cumin', 'Saffron', 'Ginger', 'Mandarin Orange', 'Wormwood'], middleNotes: ['Incense', 'Immortelle', 'Copaiba balm', 'Oliganun', 'Labdanum', 'Rose'], baseNotes: ['Licorice', 'Sandolwood', 'Cedar', 'Musk', 'Tonka Bean'], longevity: 5, sillage: 5, intensity: 5, price: 9800, season: ['Winter', 'Autumn'], occasion: 'Special' },
  { id: 'sp-6', name: 'Red Tobacco', brand: 'Mancera', gender: 'Unisex', concentration: 'EDP', scentFamily: 'Spicy', topNotes: ['Cinnamon', 'Oud', 'Saffron', 'Incense', 'Nutmeg', 'Green Apple', 'White Pear'], middleNotes: ['Patchouli', 'Jasmine'], baseNotes: ['Tobacco', 'Madagascar Vanilla', 'Amber', 'Sandalwood', 'Guaiac Wood', 'White Musk', 'Haitian Vetiver'], longevity: 5, sillage: 5, intensity: 5, price: 3800, season: ['Winter', 'Autumn'], occasion: 'Night' },
  { id: 'sp-7', name: 'Cinnabar', brand: 'Estée Lauder', gender: 'Female', concentration: 'EDP', scentFamily: 'Spicy', topNotes: ['Spices', 'Peach', 'Orange Blossom', 'Tangerine', 'Bergamot'], middleNotes: ['Cinnamon', 'Cloves', 'Ylang-Ylang', 'Jasmine', 'Lily', 'Rose'], baseNotes: ['Incense', 'Tolu Balsam', 'Amber', 'Benzoin', 'Sandalwood', 'Vanilla', 'Patchouli', 'Vetiver'], longevity: 5, sillage: 5, intensity: 5, price: 3500, season: ['Winter', 'Autumn'], occasion: 'Night' },
  { id: 'sp-8', name: 'Kenzo Elephant', brand: 'Kenzo', gender: 'Female', concentration: 'EDP', scentFamily: 'Spicy', topNotes: ['Cloves', 'Cumin', 'Mandarin Orange'], middleNotes: ['Cardamom', 'Caraway', 'Licorice', 'Mango', 'Ylang-Ylang', 'Heliotrope', 'Gardenia'], baseNotes: ['Vanilla', 'Amber', 'Patchouli'], longevity: 5, sillage: 5, intensity: 5, price: 2800, season: ['Winter', 'Autumn'], occasion: 'Special' },
  { id: 'sp-9', name: 'Black Cashmere', brand: 'Donna Karan', gender: 'Female', concentration: 'EDP', scentFamily: 'Spicy', topNotes: ['Nutmeg', 'Saffron'], middleNotes: ['Cloves', 'White Pepper', 'Rose'], baseNotes: ['Incense', 'Amber', 'Woody Notes', 'Patchouli', 'Vanilla'], longevity: 5, sillage: 4, intensity: 4, price: 5500, season: ['Winter', 'Autumn'], occasion: 'Night' },
  { id: 'sp-10', name: 'Journey Man', brand: 'Amouage', gender: 'Male', concentration: 'EDP', scentFamily: 'Spicy', topNotes: ['Sichuan Pepper', 'Cardamom', 'Bergamot', 'Neroli'], middleNotes: ['Tobacco Leaf', 'Incense', 'Juniper Berries'], baseNotes: ['Leather', 'Cypriol Oil', 'Tonka Bean', 'Musk'], longevity: 5, sillage: 4, intensity: 4, price: 10200, season: ['Winter', 'Autumn', 'Spring'], occasion: 'Special' },

  // --- LEATHER (10 total) ---
  { id: 'lt-1', name: 'Tuscan Leather', brand: 'Tom Ford', gender: 'Unisex', concentration: 'EDP', scentFamily: 'Leather', topNotes: ['Raspberry', 'Saffron', 'Thyme'], middleNotes: ['Olibanum', 'Jasmine'], baseNotes: ['Leather', 'Suede', 'Amber', 'Woody Notes'], longevity: 5, sillage: 5, intensity: 5, price: 8200, season: ['Winter', 'Autumn'], occasion: 'Night' },
  { id: 'lt-2', name: 'Ombré Leather', brand: 'Tom Ford', gender: 'Unisex', concentration: 'EDP', scentFamily: 'Leather', topNotes: ['Cardamom'], middleNotes: ['Leather', 'Jasmine Sambac'], baseNotes: ['Amber', 'Moss', 'Patchouli'], longevity: 5, sillage: 4, intensity: 4, price: 5400, season: ['Autumn', 'Winter', 'Spring'], occasion: 'Special' },
  { id: 'lt-3', name: 'Cuir de Russie', brand: 'Chanel', gender: 'Female', concentration: 'EDP', scentFamily: 'Leather', topNotes: ['Aldehydes', 'Orange Blossom', 'Bergamot', 'Mandarin Orange', 'Lemon'], middleNotes: ['Iris', 'Ylang-Ylang', 'Jasmine', 'Rose', 'Clary Sage'], baseNotes: ['Leather', 'Birch', 'Tobacco', 'Amber', 'Musk', 'Vanilla', 'Heliotrope', 'Cedar'], longevity: 4, sillage: 3, intensity: 4, price: 11000, season: ['Winter', 'Autumn'], occasion: 'Special' },
  { id: 'lt-4', name: 'Irish Leather', brand: 'Memo Paris', gender: 'Unisex', concentration: 'EDP', scentFamily: 'Leather', topNotes: ['Juniper Berries'], middleNotes: ['Mate', 'Iris'], baseNotes: ['Leather', 'Amber', 'Tonka Bean'], longevity: 4, sillage: 4, intensity: 4, price: 9200, season: ['Spring', 'Autumn', 'Winter'], occasion: 'Day' },
  { id: 'lt-5', name: 'African Leather', brand: 'Memo Paris', gender: 'Unisex', concentration: 'EDP', scentFamily: 'Leather', topNotes: ['Cardamom', 'Saffron'], middleNotes: ['Cumin', 'Geranium'], baseNotes: ['Leather', 'Oud', 'Patchouli', 'Vetiver', 'Musk'], longevity: 5, sillage: 5, intensity: 5, price: 9500, season: ['Winter', 'Autumn'], occasion: 'Night' },
  { id: 'lt-6', name: 'Dior Homme Parfum', brand: 'Dior', gender: 'Male', concentration: 'Parfum', scentFamily: 'Leather', topNotes: ['Tuscan Iris', 'Italian Orange'], middleNotes: ['Leather', 'Rose'], baseNotes: ['Sandalwood', 'Ambrette', 'Oud', 'Cedar'], longevity: 5, sillage: 5, intensity: 5, price: 5200, season: ['Winter', 'Autumn'], occasion: 'Night' },
  { id: 'lt-7', name: 'Fahrenheit', brand: 'Dior', gender: 'Male', concentration: 'EDT', scentFamily: 'Leather', topNotes: ['Nutmeg Flower', 'Lavender', 'Cedar', 'Chamomile', 'Mandarin Orange', 'Hawthorn', 'Bergamot', 'Lemon'], middleNotes: ['Violet Leaf', 'Nutmeg', 'Cedar', 'Sandalwood', 'Honeysuckle', 'Carnation', 'Jasmine', 'Lily-of-the-Valley'], baseNotes: ['Leather', 'Vetiver', 'Musk', 'Amber', 'Patchouli', 'Tonka Bean'], longevity: 5, sillage: 4, intensity: 4, price: 3400, season: ['Autumn', 'Winter', 'Spring'], occasion: 'Special' },
  { id: 'lt-8', name: 'Gucci Guilty Absolute', brand: 'Gucci', gender: 'Male', concentration: 'EDP', scentFamily: 'Leather', topNotes: ['Leather'], middleNotes: ['Cypress', 'Patchouli'], baseNotes: ['Woody Notes', 'Vetiver'], longevity: 5, sillage: 4, intensity: 5, price: 3100, season: ['Winter', 'Autumn'], occasion: 'Special' },
  { id: 'lt-9', name: 'Bel Ami', brand: 'Hermès', gender: 'Male', concentration: 'EDT', scentFamily: 'Leather', topNotes: ['Sage', 'Bergamot', 'Mandarin Orange', 'Lemon', 'Cardamom'], middleNotes: ['Patchouli', 'Carnation', 'Basil', 'Orris Root', 'Cedar', 'Jasmine'], baseNotes: ['Leather', 'Oakmoss', 'Styrax', 'Vetiver', 'Amber', 'Vanilla', 'Coconut'], longevity: 4, sillage: 3, intensity: 4, price: 3800, season: ['Autumn', 'Winter'], occasion: 'Office' },
  { id: 'lt-10', name: 'Falcon Leather', brand: 'Matiere Premiere', gender: 'Unisex', concentration: 'EDP', scentFamily: 'Leather', topNotes: ['Saffron', 'Labdanum'], middleNotes: ['Birch Tar'], baseNotes: ['Benzoin', 'Oud'], longevity: 5, sillage: 5, intensity: 5, price: 7800, season: ['Winter', 'Autumn'], occasion: 'Night' },

  // --- GOURMAND (10 total) ---
  { id: 'gm-1', name: 'Lost Cherry', brand: 'Tom Ford', gender: 'Unisex', concentration: 'EDP', scentFamily: 'Gourmand', topNotes: ['Sour Cherry', 'Bitter Almond', 'Liquor'], middleNotes: ['Sour Cherry', 'Plum', 'Turkish Rose', 'Jasmine Sambac'], baseNotes: ['Tonka Bean', 'Vanilla', 'Peru Balsam', 'Benzoin', 'Cinnamon', 'Sandalwood', 'Cedar', 'Cloves', 'Vetiver', 'Patchouli'], longevity: 4, sillage: 3, intensity: 4, price: 12500, season: ['Autumn', 'Winter'], occasion: 'Date' },
  { id: 'gm-2', name: 'Candy', brand: 'Prada', gender: 'Female', concentration: 'EDP', scentFamily: 'Gourmand', topNotes: ['Caramel'], middleNotes: ['Powdery Notes', 'Musk'], baseNotes: ['Benzoin', 'Vanilla'], longevity: 3, sillage: 3, intensity: 3, price: 3200, season: ['Autumn', 'Winter'], occasion: 'Day' },
  { id: 'gm-3', name: 'Lira', brand: 'Xerjoff', gender: 'Female', concentration: 'EDP', scentFamily: 'Gourmand', topNotes: ['Blood Orange', 'Bergamot', 'Lavender'], middleNotes: ['Cinnamon', 'Licorice', 'Jasmine'], baseNotes: ['Caramel', 'Vanilla', 'Musk'], longevity: 5, sillage: 4, intensity: 4, price: 7800, season: ['Winter', 'Autumn'], occasion: 'Special' },
  { id: 'gm-4', name: 'Chocolate Greedy', brand: 'Montale', gender: 'Unisex', concentration: 'EDP', scentFamily: 'Gourmand', topNotes: ['Cacao', 'Vanilla'], middleNotes: ['Tonka Bean', 'Bitter Orange'], baseNotes: ['Coffee', 'Dried Fruits'], longevity: 5, sillage: 5, intensity: 5, price: 2900, season: ['Winter'], occasion: 'Night' },
  { id: 'gm-5', name: 'By the Fireplace', brand: 'Maison Margiela', gender: 'Unisex', concentration: 'EDT', scentFamily: 'Gourmand', topNotes: ['Cloves', 'Pink Pepper', 'Orange Blossom'], middleNotes: ['Chestnut', 'Guaiac Wood', 'Juniper'], baseNotes: ['Vanilla', 'Peru Balsam', 'Cashmeran'], longevity: 4, sillage: 3, intensity: 3, price: 4200, season: ['Winter', 'Autumn'], occasion: 'Day' },
  { id: 'gm-6', name: 'Italica', brand: 'Xerjoff', gender: 'Unisex', concentration: 'EDP', scentFamily: 'Gourmand', topNotes: ['Almond', 'Milk', 'Saffron'], middleNotes: ['Toffee', 'Bourbon Vanilla'], baseNotes: ['Sandalwood', 'White Musk'], longevity: 5, sillage: 5, intensity: 5, price: 8800, season: ['Winter'], occasion: 'Special' },
  { id: 'gm-7', name: 'Hypnotic Poison', brand: 'Dior', gender: 'Female', concentration: 'EDT', scentFamily: 'Gourmand', topNotes: ['Coconut', 'Plum', 'Apricot'], middleNotes: ['Brazilian Rosewood', 'Jasmine', 'Caraway', 'Tuberose', 'Rose', 'Lily-of-the-Valley'], baseNotes: ['Vanilla', 'Almond', 'Sandalwood', 'Musk'], longevity: 5, sillage: 4, intensity: 4, price: 3800, season: ['Winter', 'Autumn'], occasion: 'Date' },
  { id: 'gm-8', name: 'Baccarat Rouge 540', brand: 'Maison Francis Kurkdjian', gender: 'Unisex', concentration: 'EDP', scentFamily: 'Gourmand', topNotes: ['Saffron', 'Jasmine'], middleNotes: ['Amberwood', 'Ambergris'], baseNotes: ['Fir Resin', 'Cedar'], longevity: 5, sillage: 5, intensity: 5, price: 13500, season: ['Autumn', 'Winter', 'Spring'], occasion: 'Special' },
  { id: 'gm-9', name: 'Black Phantom', brand: 'By Kilian', gender: 'Unisex', concentration: 'EDP', scentFamily: 'Gourmand', topNotes: ['Dark Chocolate'], middleNotes: ['Rum', 'Caramel', 'Coffee', 'Sugar Cane'], baseNotes: ['Almond', 'Sandalwood', 'Heliotrope'], longevity: 5, sillage: 4, intensity: 4, price: 9200, season: ['Winter', 'Autumn'], occasion: 'Night' },
  { id: 'gm-10', name: 'Khamrah', brand: 'Lattafa', gender: 'Unisex', concentration: 'EDP', scentFamily: 'Gourmand', topNotes: ['Cinnamon', 'Nutmeg', 'Bergamot'], middleNotes: ['Dates', 'Praline', 'Tuberose', 'Mahonial'], baseNotes: ['Vanilla', 'Tonka Bean', 'Amberwood', 'Myrrh', 'Benzoin', 'Akigalawood'], longevity: 5, sillage: 5, intensity: 5, price: 1500, season: ['Winter', 'Autumn'], occasion: 'Night' }
];

export const SCENT_FAMILIES = [
  'Floral', 'Woody', 'Oriental', 'Fresh', 'Citrus', 'Spicy', 'Leather', 'Gourmand'
];

export const CONCENTRATIONS = ['EDP', 'EDT', 'Parfum', 'Cologne', 'Extrait'];

export const GENDER_TYPES = ['Male', 'Female', 'Unisex'];

export const POPULAR_NOTES = [
  'Vanilla', 'Rose', 'Jasmine', 'Sandalwood', 'Bergamot', 'Patchouli', 'Musk', 'Amber',
  'Cedar', 'Lavender', 'Lemon', 'Orange', 'Iris', 'Peony', 'Oud', 'Vetiver', 'Tobacco',
  'Leather', 'Cinnamon', 'Cherry', 'Chocolate', 'Coffee', 'Caramel', 'Pineapple', 'Mint'
];

export const OCCASIONS = ['Day', 'Night', 'Office', 'Date', 'Special'];
export const SEASONS = ['Spring', 'Summer', 'Autumn', 'Winter'];
